### ISSUE TITLE
I'm dumb, what is this?

### ISSUE THREAD

**Issue by enigma9o7** [sm64js/sm64js#1]
that's pretty much it

I feel like this is something web or mobile related. Or maybe a way to run the port on older platforms?  Although ogl 1.3 seems old enough so maybe not.

I've done the WEB_TARGET=1 build on the port and tried what comes out.  It has .js files too but also a html and when I host it it makes sense.

But how do you run this?  or what do you do with it?

**Comment by sm64js** [comment]
Hi @enigma9o7 ,

I don't think any of these are dumb questions, I expected some confusion here.

I took my [website ](http://snuffymatt.me/)down temporarily, because I was warned about hosting Nintendo textures.  I just put it back up with the game removed for now, it explains many of the questions you are asking. But I'll answer them here as well.

> What is this?  

This is me rewriting / porting the C code manually into native Javascript

> I've done the WEB_TARGET=1 build on the port and tried what comes out. It has .js files too but also a html and when I host it it makes sense.

Yep, that compiles the C code into web assembly.  And it works really well, probably works on as many devices and platforms as my port would, and probably at similar (or better?) performance (I don't really know tbh).  My motivation to make a native javascript port started because I wanted to build some multiplayer custom games and wanted to interface with the code more easily for that. But the main motivations for me anyways I list on that website Iinked above. In summary, I saw value in the rewriting the code in javascript or any higher level language because I believed it would open the door to more developers that may want to make custom content but aren't experienced in low level programming like C.  Additionally, even for people that are experienced in C, like myself, I started this project so I can more easily interface and add other software packages and tools that I may want to use to make other custom content.

>But how do you run this? or what do you do with it?

I haven't shared instructions for this yet, but I will.  But I am using nodejs babel and webpack to build/compile the runnable javascript.   You'd need to install node and npm,  and then I think you'd just need to do something like 
`npm install
npm run build`

then that will put the index.html and index.js in the /dist folder and you can launch and run that.

or host the site by

`node serveProduction.js`

There might be other steps necessary, I'll look into that and see if I can make the process more simple

**Comment by sm64js** [comment]
Build / Run Instructions have been added btw

**Comment by justabluemouse** [comment]
Oops, didn't mean to mention this 👀
