### ISSUE TITLE
I have a question. What made you start sm64js in the 1st place?

### ISSUE THREAD

**Issue by FallGuy308** [sm64js/sm64js#190]
yes, i know this isnt an issue, but i dont know where else to contact you

**Comment by luphoria** [comment]
If you have any inquiry/interview to snuffysasa, the best way to contact him is via the Discord server. If you have a more serious contact issue (business inquiry) then you could try his email. Perhaps another AMA should be done (again, in the Discord server)?

**Comment by sm64js** [comment]
When I found out about the n64 decomp project and open source code for the sm64 pc port, I was really excited and knew I wanted to do something.  I started messing around with the code and started thinking about how I could make a multiplayer mod.  I was thinking, that this would be easier for me to do with websockets since I had more experience there. I think I was messing around with the emscripten WASM port and was thinking about how to integrate javascript with it.  Then the amusing thought just occurred to me that since whole project is open source, the whole thing could be made into JavaScript.  That thought was entirely amusing to me and made me laugh out loud. Around then I decided to start sm64js as a joke just to see if I could get anything to happen or get the intro menu to load. I had no idea the project would lead to where it is now.
