### ISSUE TITLE
tiny house at the tiny pool in CCM won't let you in due to an invisible barrier. that might be intentional, but it could of been awesome if we could go in.

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#206]
Yes it could be a bug, but it might also be intentional. i and many people tried clipping into it and it's all insible wall/barrier. if a desinger could be able to add like custom furniture that would be epic.

**Comment by NoveltyMan** [comment]
I guess that it was intentional.
The model used for the collision is the same as in the original game.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

pon., 11 sty 2021 o 18:22 Someone567123 <notifications@github.com>
napisał(a):

**Comment by github10omar** [comment]
Yip

**Comment by github10omar** [comment]
Yup, that's true. In game, if you manage to use the L fly code at the right moment while still behind the door, you will fall as there is no collision. So that's why there is a wall. (in game means the real sm64 on the emu/n64, depends)

**Comment by sm64js** [comment]
yea, eventually we can add this
