### ISSUE TITLE
Can you make the Nintendo⁶⁴ Controller Compatible?

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#328]
Hi, _SM64JS player_ Oweblow here. I got a new _Nintendo⁶⁴ Controller_ since my _TGZ one had a faulty A button_. And I saw it _wasn't compatible with SM64JS_. Can you please fix it?

**Comment by Warrior555MainsGanon** [comment]
Can't tell if the n64 controller is actually supported or not (cuz it might as well be just an issue on your end), but in the case the n64 controller is indeed unsupported, where would we bind the new buttons? (the only buttons left on a n64 con are L and R, but the buttons to be bound are minimap, taunt wheel and glide) IMO it should be taunt wheel on L, glide on R and nothing for minimap since it's used only in few maps as far as I know.

**Comment by luphoria** [comment]
This is most likely on your end/we likely cant add support for it. Does it show up as a gamepad at all when you plug it in your PC?

**Comment by ghost** [comment]
_Luphoria_, _it recognizes it_ as my _old TGZ controller_ even though it _isn't even on_, I have my _Nintendo⁶⁴_ controller plugged in instead.

**Comment by justabluemouse** [comment]
even though they probably can't, would be poggers if they added n64 controller support, maybe CRT filter for nostalgia?????? a mere possibilty

**Comment by Cooliokid956** [comment]
if it's not supported, you can probably find a program to convert n64 controller input to xinput

**Comment by ghost** [comment]
Ok... @Cooliokid956

**Comment by luphoria** [comment]
Feature

**Comment by luphoria** [comment]
jk its just not something we can fix

**Comment by ghost** [comment]
Oh... @luphoria
