### ISSUE TITLE
Leave the guy alone

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#365]
Little birdie told me you guys are falsely accusing someone of being me. I had no plans of ever talking to you guys again until I heard about this. Please leave the guy alone. No I am not him. I do my own thing now. I mod games instead and I couldn't be happier with my life. You guys had taught me something and it went a long way. Thank you.

**Comment by ghost** [comment]
I still keep tabs on this game you know

**Comment by luphoria** [comment]
Hello,

Your account was disabled for violating our Terms of Service or Community Guidelines. We’ve reviewed and have confirmed this violation, and we will not be reinstating your account.

**Comment by Cooliokid956** [comment]
give us one thing you've done besides try to come back

**Comment by ghost** [comment]
I was a jerk yes. I deserved all you gave me. This guy doesn't, he did nothing wrong. I have proof I'm not him if you would like to see

**Comment by AgentXLP** [comment]
Quit lying you fucking carnival lmfao

**Comment by Cooliokid956** [comment]
Little birdie told you to shut the fuck up

**Comment by luphoria** [comment]
Hello,

Your account was disabled for violating our Terms of Service or Community Guidelines. We’ve reviewed and have confirmed this violation, and we will not be reinstating your account.

**Comment by AgentXLP** [comment]
:trollface:

**Comment by Cooliokid956** [comment]
[you](https://cdn.discordapp.com/attachments/755122837077098633/851587234267660288/b0d.png)

**Comment by ghost** [comment]
Alright, this guy practically sent a message the same time I did.
[](url)
![Screenshot 2021-06-07 3 24 03 PM](https://user-images.githubusercontent.com/75806962/121095128-98612780-c7a4-11eb-91cf-6f647762dc3f.png)
![Screenshot 2021-06-07 3 23 17 PM](https://user-images.githubusercontent.com/75806962/121095131-98f9be00-c7a4-11eb-96d9-5c6948dcc91c.png)

This means we absolutely cant be the same

**Comment by ghost** [comment]
You cant be signed into 2 different accounts at the same time.

**Comment by Cooliokid956** [comment]
why are you supporting our claims

**Comment by Cooliokid956** [comment]
> You cant be signed into 2 different accounts at the same time.

you can sign out though

**Comment by Cooliokid956** [comment]
certified r/quityourbullshit moment

**Comment by ghost** [comment]
In the same minute? I dont think anyone is fast enough

**Comment by AgentXLP** [comment]
that moment when
when incognito exists
when multiple users exist
when different devices exist
quit bullshiting :morphoff:

**Comment by Cooliokid956** [comment]
tabs moment

**Comment by ghost** [comment]
Please unban this guy. The only thing he did wrong is call you corrupt

**Comment by Cooliokid956** [comment]
the only thing he did wrong is you

**Comment by ghost** [comment]
> that moment when
> when incognito exists
> when multiple users exist
> when different devices exist
> quit bullshiting :morphoff:

I cant do any of that actually

**Comment by AgentXLP** [comment]
> > that moment when
> > when incognito exists
> > when multiple users exist
> > when different devices exist
> > quit bullshiting :morphoff:
> 
> I cant do any of that actually

sure buddy
suurree

**Comment by Cooliokid956** [comment]
> > that moment when
> > when incognito exists
> > when multiple users exist
> > when different devices exist
> > quit bullshiting :morphoff:
> 
> I cant do any of that actually

you definitely can

**Comment by luphoria** [comment]
Hello,

Your account was disabled for violating our Terms of Service or Community Guidelines. We’ve reviewed and have confirmed this violation, and we will not be reinstating your account.

I request you stop interacting with this community. Where do you think this will get you?

**Comment by Cooliokid956** [comment]
> Hello,
> 
> Your account was disabled for violating our Terms of Service or Community Guidelines. We’ve reviewed and have confirmed this violation, and we will not be reinstating your account.
> 
> I request you stop interacting with this community. Where do you think this will get you?

getting trolled that's what

**Comment by AgentXLP** [comment]
Imagine this; SMB575 gets on his old account to try to unjustify his ban which was proven in various ways such as ISP, speech, ect, you are the opposite of sneaky or clever, go outside; make contact with grass, literally nothing is saving you, everybody knows what you did, tf outta here.

**Comment by ghost** [comment]
Alright well if I cant get you to reason then there is not much I can do. I can see you guys didn't change any. All I hope is that you guys learn and make sure you are certain before you ban anyone. You guys have a great day, I wish you best!

**Comment by Cooliokid956** [comment]
> Alright well if I cant get you to reason then there is not much I can do. I can see you guys didn't change any. All I hope is that you guys learn and make sure you are certain before you ban anyone. You guys have a great day, I wish you best!

we are very certain
goodbye

**Comment by AgentXLP** [comment]
> Alright well if I cant get you to reason then there is not much I can do. I can see you guys didn't change any. All I hope is that you guys learn and make sure you are certain before you ban anyone. You guys have a great day, I wish you best!

We are certain, it is you, the amount of bullshit you are speaking is insane, I will know when you come on again, fear that piece of intel.

**Comment by ghost** [comment]
@sm64js @snuffysasa I request that you truly look over your admins behaviors and actions.

**Comment by Cooliokid956** [comment]
he'd probably feel the same if he were active

**Comment by ghost** [comment]
I just hope that they end up representing you correctly

**Comment by AgentXLP** [comment]
> @sm64js @snuffysasa I request that you truly look over your admins behaviors and actions.

dw about it, he can find out pretty easily what happened with you

**Comment by luphoria** [comment]
> @sm64js @snuffysasa I request that you truly look over your admins behaviors and actions.

i have already begun contact about this issue, it is under control. Good day

**Comment by ghost** [comment]
Yeah, stuff happened with me. I am free and happy now. Im going to go and continue living that way. I wish you best mysterio. Fight for what is right always.

**Comment by Cooliokid956** [comment]
that's you you dumbfuck (OMG GUYS HE MADE A SPELLING MISTAKE AND EDITED IT OH MY GOSH AAAAAAAAAAAAAAAAA)

**Comment by luphoria** [comment]
> Yeah, stuff happened with me. I am free and happy now. Im going to go and continue living that way. I wish you best mysterio. Fight for what is right always.

"I am free and happy now"
"I still keep tabs on this game you know"

Something aint lining up here. Oh well.

**Comment by ghost** [comment]
Fuck you @supermariobros575 its your fault anyway

**Comment by AgentXLP** [comment]
I even wrote an entire storybook about you :D here, let me send it.

The story of the Entire Damn Carnival by Agent X

Tried to revoke Someone567123's admin a couple times,

Used "dark side" RP to justify flat out insulting others,

Weaponized suicide to force people to agree with him once he realized he wasn't going anywhere with his argument,

Got extremely disrespectful and fully in violation of the literal first rule of the sm64js server which is to respect others that actually deserve respect,

SMB575 returns, by an unexplainable miracle or should I say mistake, is forgiven even though the list is starting to pile up from here on out.

Pretends he has a "secret admirer" and then gets caught in another big fat lie because he literally shares the same ID with the real SMB575, if that wasn't enough...

SMB575 threatens to leak luphoria's IRL face which is literal concrete hard blackmail, and when looked down upon he says "Ay, don't be a bitch, stuff won't happen." and remember he literally had luphoria's face at his disposal and he could leak it oh but he wouldn't out of respect!!! Totally not another lie!!! From there the majority of the people there realize how human garbage he truly is, yet he proceeds to cause havoc from the shadows.

SMB575 wants his wiki page full of all of the awful things he has done deleted since if people see who he truly is it will ruin any relationship he can sustain between them, unfortunately Fandom is like Git and you can just rollback changes kek.

Agent X with the help of Cooliokid 956 is able to figure out that SMB575 stole Agent X's HTML code for his website initially and tried to play it off saying luphoria said he could when the DM he posted was mentioning sm64js only, no involvement with Agent X or his code. SMB575 did this without Agent X's knowledge what so ever until Cooliokid 956 figured it out in the original commits for SMB575's GitHub.io.

The idiot returns, SMB575 is back in full force on an alt named "Unnamed Potato" to spy on the sm64js server and trying to learn from Agent X on how to fully import custom maps himself without the help of 0x2480, the head custom map designer and importer for sm64js MMO to retrace his steps as his past self and re-obtain the developer role, sneaky but Cooliokid 956 comes to the rescue again and with sm64js's admin panel is able to realize a shocking truth, Unnamed Potato shares the same exact IP and ISP as SMB575 does, Agent X realizes Unnamed Potato, secretly but not for long SMB575 has an interest in SMB575, pretending like they are different people, this does not go unnoticed under the watchful eye of Agent X who realizes this and tests Unnamed Potato in DMS with various questions to see how similar to SMB575 he was, and they seemed strikingly similar, it was then fully exposed with evidence now public who Unnamed Potato truly was, when Agent X confronted him about his true self, he didn't even put up a show for the entire circus he is, he again tries to play the weaponizing of suicide card to gain leverage in the people in his community, unfortunately for him nobody is going to let history repeat itself and then force Unnamed Potato out of all of the sm64js servers such as Laki's private friend server and the official one.

From the twitter paragraph you have read above, he is 2 sided, toxic and a pathological piece of absolute shit liar and an absolute fucking joke for representing what is to be a human being, let this text file be known as history itself and never to emulate this child's actions remotely at all.

May 22nd, 2021 Update:
Account deletion

June 7th, 2021 Update:
Carnival returns on an alt named "Mysterio" and gets caught by various English inspections, and an IP check, he tries to say he is not but the evidence is too substantial and is banned by luphoria, then he goes on GitHub to complain about it and goes on his previous account "supermariobros575" to attempt to act like they are different people but are we also a fucking carnival? Not likely. This is very seethrough as a blatant lie because what a funny coincidence spookymariobroth575 comes back magically to tell us his alt is good! 😒

**Comment by Cooliokid956** [comment]
> Fuck you @supermariobros575 its your fault anyway

nice acting

**Comment by AgentXLP** [comment]
> Fuck you @supermariobros575 its your fault anyway

When the acting is bullshit

**Comment by Cooliokid956** [comment]
this encounter was very fun to watch

**Comment by AgentXLP** [comment]
> this encounter was very fun to watch

It's a shame RPG [TV Mario] couldn't watch it play out live.

**Comment by Cooliokid956** [comment]
what makes this even more funny is that there was no contact between both at one time, which is a stupidass giveaway

**Comment by AgentXLP** [comment]
> what makes this even more funny is that there was no contact between both at one time, which is a stupidass giveaway

It is already so obvious anyways

**Comment by ghost** [comment]
Btw I should note: You got the wrong account. Im actually under a different name in sm64js. So if you want to make this a game, fine. Let us play...

**Comment by 0x2480** [comment]
cringe

**Comment by ghost** [comment]
Real

**Comment by ghost** [comment]
And now, I disapear again. And I wont be found.

**Comment by Cooliokid956** [comment]
sounds very edgy

**Comment by ghost** [comment]
Nah, you may consider this another "show". Im a circus right? Then you better be ready for a show!

**Comment by AgentXLP** [comment]
> Btw I should note: You got the wrong account. Im actually under a different name in sm64js. So if you want to make this a game, fine. Let us play...

Dw, I'll IP ban you rn :trollwink:

**Comment by Cooliokid956** [comment]
i am cringing hard right now

**Comment by ghost** [comment]
> when different devices exist

And yet another account to self dustruct

**Comment by ghost** [comment]
On week 3, when the sun is high
The shadows disappear, and out comes the enemy

**Comment by ghost** [comment]
Bye

**Comment by luphoria** [comment]
![Screenshot_20210607-175521.jpg](https://user-images.githubusercontent.com/60309933/121097418-905fb280-c7b9-11eb-85ff-03769194e945.jpg)

**Comment by AgentXLP** [comment]
> On week 3, when the sun is high
> The shadows disappear, and out comes the enemy

Oh noes, edgy kid being edgy, crazy

**Comment by ghost** [comment]
You want a circus? You got one.

**Comment by AgentXLP** [comment]
> You want a circus? You got one.

No, I want you to get a life, not be a **carnival** and continue being a fuckin TF2 spy

**Comment by eros71-dev** [comment]
Please SMB575 I've tried to respect you and you do this man... Leave github for the actual issues.

**Comment by Cooliokid956** [comment]
rename moment

**Comment by blueknight64** [comment]
Dear smb575,


QUIT YOUR FUCKING BULLSHIT! THE COMMUNITY HAS ENOUGH OF YOU!

**Comment by justabluemouse** [comment]
dang it, i missed out on sm64js drama again

**Comment by justabluemouse** [comment]
(just gonna throw in my two cents here) even if this wasn't you(totally not you), then why would you care so much about this "diFFerEnT" user. after all, there are multiple sm64js users that have gotten banned, and yet, for some reason, you care about this _**one**_  specific user. You could be honest and just drop it. If you really don't want this, then just back off. Really.
