### ISSUE TITLE
The Google sign-in ain't working

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#620]
I'm not telling you how I got here, all I'm telling you is you need to fix the sign-in.
![image](https://user-images.githubusercontent.com/92883596/149296733-5d8dc7ac-88e7-4a91-a515-3dd52dd3d50e.png)

**Comment by Tarnadas** [comment]
This redirect_uri is the fallback/default for local development (see [here](https://github.com/sm64js/sm64js/blob/MMO/package.json#L11)), which proves to me, that you're trying to play on official servers with your own modified version. As stated in #616, this does not work and is for obvious reasons not allowed.

Since you're repeatedly trying to hack in-game and are spamming us with issues on Github, I have to report this.

**Comment by ImaginaryNeon** [comment]
what? I just stumbled upon that while looking around out of boredom. And do you mean a modified ROM of sm64?

**Comment by blueknight64** [comment]
My dude, this is github not discord, if you wanna ask some stuff like how to help the dev team then go to the discord server, which i doubt your even OLD enough. And Tarnadas already mentioned that it’s not allowed.

**Comment by eros71-dev** [comment]
> what? I just stumbled upon that while looking around out of boredom. And do you mean a modified ROM of sm64?

I'm sure that loading a modified rom would not cause a login problem. Please use GitHub for real game issues. Not being able to log in with a modified version is intended and not an issue. And by the way, not telling us what steps you followed to get that error wouldn't help us fix it either if this was a real problem.

**Comment by ImaginaryNeon** [comment]
> My dude, this is github not discord, if you wanna ask some stuff like how to help the dev team then go to the discord server, which i doubt your even OLD enough. And Tarnadas already mentioned that it’s not allowed.

I'm kinda banned from the Discord for posting a gun image at a bad time.
