### ISSUE TITLE
Player turning red glitch

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#682]
So i was in Mushroom Battlefield and there was a player named Wario. I was going to longjump off of his head cuz funni but i accidently hit him in the process. But instead of the damage meter decreasing, he turned bright red like you do when you get damaged in Minecraft and then left.
I don't know if I was seeing things or it was a glitch or if it's a new update.

**Comment by Bloxxel64** [comment]
What was his color scheme?

**Comment by AgentXLP** [comment]
That seems more like they just changed their CC and left

**Comment by ghost** [comment]
His color scheme was just regular Wario colors and right before he left, he turned red so i don't think it was him changing his cc to red THAT fast.

**Comment by ImaginaryNeon** [comment]
> His color scheme was just regular Wario colors and right before he left, he turned red so i don't think it was him changing his cc to red THAT fast.

I mean keep in mind that color codes can be pasted in, and that the AFK timer exists.
Did you see him in another map later? And if so, was he still red?

**Comment by ghost** [comment]
I did not see him in another map and i haven't seen him since.

**Comment by ImaginaryNeon** [comment]
> I did not see him in another map and i haven't seen him since.

It still seems like he just changed his color code and left/got AFK kicked. I think he was likely AFK kicked, though, because changing one's color code does not count as an action. (In the sense that it doesn't reset the AFK timer.)
It _**could **_be possible that the color sliders bugged out on his side while he was messing with them, but I feel like that's just grasping at straws.

**Comment by MatthewMario64** [comment]
> That seems more like they just changed their CC and left

This is common, people are able to change their color and get kicked.
