### ISSUE TITLE
Can't start a game in SM64JS

### ISSUE THREAD

**Issue by g3-geo** [sm64js/sm64js#709]
(Mr. Yahoo btw lo) ive recently posted a video showing that when i try joining a game, it just refreshes the site lo
i have a z64 file put in and are logged in already, it'll just keep refreshing the site whenever i press submit
--------
video for whats going on: https://www.youtube.com/watch?v=4H9S6wYUI3s

**Comment by g3-geo** [comment]
help lo, and birds are cool

**Comment by vanillaDSi** [comment]
I had that same issue yesterday while playing with you, as well. I also reported the glitch with a more lengthy recording (where I tried to open the website in a different tab) and I had the same issue. I think it may be caused by an issue in the website's function to remember a user's history of using the site.

**Comment by AgentXLP** [comment]
Deploying fix
